name: Maven build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags-ignore:
      - "release-*"

jobs:
  build:
    runs-on: deere-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build maven
        run: |
          mvn -B -V -e -s settings.xml $MVN_COMMAND -Djansi.force=true -Dmaven.test.failure.ignore -Dartifactory.user=${{ secrets.ARTIFACTORY_USERNAME }} -Dartifactory.password=${{ secrets.ARTIFACTORY_PASSWORD }}
        env:
          MVN_COMMAND: ${{ github.ref_name == 'main' && 'clean deploy' || 'clean install' }}
